// Replays tests/fixtures/frame_diffs: the bytes a real differential TUI
// renderer sent to turn one frame into the next, and the frame it meant to
// leave on screen (generated by scripts/frame-diffs, which explains how).
// After each frame's bytes the screen must be that frame -- its text, its
// colours and its bold, italic and reverse cells.
//
// A renderer like this is what draws most full-screen programs, and it picks
// the cheapest sequence for every change: erase or repeat characters, insert
// or delete them, scroll a region, move by tab stops or backspace, rely on
// erases taking the current background. Any of those the engine gets wrong
// shows up here as a frame that is not what the program drew.

use std::fs;
use std::path::Path;

use tako_core::grid::{CellAttrs, Color};
use tako_core::terminal::Terminal;

struct Row {
    text: String,
    fg: Vec<String>,
    bg: Vec<String>,
    attrs: Vec<String>,
}

struct Frame {
    sent: Vec<u8>,
    rows: Vec<Row>,
}

struct Case {
    id: String,
    cols: usize,
    rows: usize,
    frames: Vec<Frame>,
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap()).collect()
}

fn words(s: &str) -> Vec<String> {
    s.split(' ').map(str::to_string).collect()
}

fn load(profile: &str) -> Vec<Case> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/frame_diffs").join(format!("{profile}.txt"));
    let text = fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let mut cases: Vec<Case> = Vec::new();
    for line in text.lines() {
        let (key, rest) = line.split_once(' ').unwrap_or((line, ""));
        match key {
            "#" | "end" => {}
            "case" => {
                let (id, size) = rest.split_once(' ').unwrap();
                let (cols, rows) = size.split_once('x').unwrap();
                cases.push(Case { id: id.to_string(), cols: cols.parse().unwrap(), rows: rows.parse().unwrap(), frames: Vec::new() });
            }
            "frame" => cases.last_mut().unwrap().frames.push(Frame { sent: Vec::new(), rows: Vec::new() }),
            "sent" => cases.last_mut().unwrap().frames.last_mut().unwrap().sent = unhex(rest),
            "row" => cases.last_mut().unwrap().frames.last_mut().unwrap().rows.push(Row {
                text: String::from_utf8(unhex(rest)).unwrap(),
                fg: Vec::new(),
                bg: Vec::new(),
                attrs: Vec::new(),
            }),
            "fg" | "bg" | "at" => {
                let row = cases.last_mut().unwrap().frames.last_mut().unwrap().rows.last_mut().unwrap();
                let list = match key {
                    "fg" => &mut row.fg,
                    "bg" => &mut row.bg,
                    _ => &mut row.attrs,
                };
                *list = words(rest);
            }
            other => panic!("{}: unknown line {other:?}", path.display()),
        }
    }
    cases
}

fn color(c: Color) -> String {
    match c {
        Color::Default => "-".to_string(),
        Color::Indexed(n) => format!("i{n}"),
        Color::Rgb(r, g, b) => format!("r{r:02x}{g:02x}{b:02x}"),
    }
}

fn attrs(a: CellAttrs) -> String {
    let mut s = String::new();
    if a.contains(CellAttrs::BOLD) {
        s.push('b');
    }
    if a.contains(CellAttrs::ITALIC) {
        s.push('i');
    }
    if a.contains(CellAttrs::REVERSE) {
        s.push('r');
    }
    if s.is_empty() { "-".to_string() } else { s }
}

/// The first way the screen differs from `frame`, if it does. Blank cells
/// are compared by background only: a renderer erases them, and an erase
/// says nothing about foreground or attributes.
fn difference(term: &Terminal, frame: &Frame) -> Option<String> {
    for (r, want) in frame.rows.iter().enumerate() {
        let cells: Vec<_> = term.viewport_row(r).into_iter().filter(|c| !c.is_wide_spacer).collect();
        let text: String = cells.iter().map(|c| if c.char == '\0' { ' ' } else { c.char }).collect();
        if text != want.text {
            return Some(format!("row {r}\n   got {text:?}\n  want {:?}", want.text));
        }
        for (i, (cell, ch)) in cells.iter().zip(want.text.chars()).enumerate() {
            let bg = color(cell.bg);
            if bg != want.bg[i] {
                return Some(format!("row {r} cell {i} ({ch:?}) background {bg}, want {}", want.bg[i]));
            }
            if ch == ' ' {
                continue;
            }
            let fg = color(cell.fg);
            if fg != want.fg[i] {
                return Some(format!("row {r} cell {i} ({ch:?}) foreground {fg}, want {}", want.fg[i]));
            }
            let at = attrs(cell.attrs);
            if at != want.attrs[i] {
                return Some(format!("row {r} cell {i} ({ch:?}) attributes {at}, want {}", want.attrs[i]));
            }
        }
    }
    None
}

fn replay(profile: &str) {
    let cases = load(profile);
    assert!(!cases.is_empty());
    let mut failures = Vec::new();
    for case in &cases {
        let mut term = Terminal::new(case.cols, case.rows);
        for (n, frame) in case.frames.iter().enumerate() {
            term.feed(&frame.sent);
            if let Some(diff) = difference(&term, frame) {
                failures.push(format!("case {} ({}x{}) frame {n}: {diff}", case.id, case.cols, case.rows));
                break;
            }
        }
    }
    assert!(
        failures.is_empty(),
        "{profile}: {} of {} cases left a different frame than the renderer drew:\n{}",
        failures.len(),
        cases.len(),
        failures.iter().take(8).cloned().collect::<Vec<_>>().join("\n")
    );
}

#[test]
fn frames_drawn_for_xterm_256color_arrive_as_drawn() {
    replay("xterm");
}

#[test]
fn frames_drawn_with_every_sequence_arrive_as_drawn() {
    replay("all-sequences");
}
