/*
 * tako — Terminal emulator
 * Copyright (c) 2026 Alexander Panasenko
 *
 * Contact: alex@prod.codes
 * Author: https://prod.codes/about/
 * Project: https://github.com/alex09x/tako
 * SPDX-License-Identifier: MIT
 */

use std::sync::atomic::{AtomicBool, AtomicU16, Ordering};
pub(crate) use std::sync::{Arc, Mutex};
pub(crate) use std::time::{Duration, Instant};

use russh::server::Server as _;
pub(crate) use tako_core::ssh::{SshAuth, SshConfig, SshEvents, SshPrompt, SshSession};

use super::server::*;

// ── The host side ────────────────────────────────────────────────────────────

/// One question the transport passed up, as the host saw it.
#[derive(Clone, Debug)]
pub(crate) struct Challenge {
    pub(crate) id: u64,
    pub(crate) name: String,
    pub(crate) instructions: String,
    pub(crate) prompts: Vec<SshPrompt>,
}

#[derive(Default)]
pub(crate) struct Recorder {
    pub(crate) connected: AtomicBool,
    pub(crate) data: Mutex<Vec<u8>>,
    pub(crate) closed: Mutex<Option<String>>,
    /// Everything that was ever asked, in order.
    pub(crate) asked: Mutex<Vec<Challenge>>,
    /// Asked but not yet handed to the plan.
    pub(crate) unserved: Mutex<Vec<Challenge>>,
}

impl Recorder {
    pub(crate) fn take_unserved(&self) -> Vec<Challenge> {
        std::mem::take(&mut *self.unserved.lock().unwrap())
    }
}

pub(crate) struct Events(pub(crate) Arc<Recorder>);

impl SshEvents for Events {
    fn on_host_key(&self, _algorithm: String, _fingerprint: String) -> bool {
        true
    }

    /// Records and returns. Answering from here would be the bug this whole
    /// design exists to avoid: on a phone this call arrives on the transport's
    /// thread and the answer comes from the user, much later.
    fn on_keyboard_interactive(
        &self,
        challenge_id: u64,
        name: String,
        instructions: String,
        prompts: Vec<SshPrompt>,
    ) {
        let challenge = Challenge {
            id: challenge_id,
            name,
            instructions,
            prompts,
        };
        self.0.asked.lock().unwrap().push(challenge.clone());
        self.0.unserved.lock().unwrap().push(challenge);
    }

    fn on_connected(&self) {
        self.0.connected.store(true, Ordering::SeqCst);
    }
    fn on_data(&self, data: Vec<u8>) {
        self.0.data.lock().unwrap().extend_from_slice(&data);
    }
    fn on_closed(&self, reason: String) {
        *self.0.closed.lock().unwrap() = Some(reason);
    }
}

/// How the host answers what it is asked. Called from the test's own thread,
/// never from the callback, because that is how a real host works.
type Plan = Box<dyn Fn(&Challenge, &SshSession) + Send>;

/// A host that is never asked anything.
pub(crate) fn unasked() -> Plan {
    Box::new(|challenge, _| panic!("nothing should have been asked, got {challenge:?}"))
}

/// A host that answers each round from a script, in order.
pub(crate) fn answering(rounds: &'static [&'static [&'static str]]) -> Plan {
    Box::new(move |challenge, session| {
        let round = rounds
            .get((challenge.id - 1) as usize)
            .unwrap_or_else(|| panic!("asked {} times, script has {}", challenge.id, rounds.len()));
        let answers = round.iter().map(|s| s.to_string()).collect();
        session.answer_keyboard_interactive(challenge.id, answers);
    })
}

/// What one connection did.
pub(crate) struct Attempt {
    /// The screen on success, the reason on failure.
    pub(crate) outcome: Result<String, String>,
    pub(crate) asked: Vec<Challenge>,
}

// ── The fixture ──────────────────────────────────────────────────────────────

/// A running server, on its own port, stopped when dropped.
pub(crate) struct Fixture {
    pub(crate) port: u16,
    pub(crate) served: Arc<AtomicBool>,
    /// The private key the client should use, when the policy wants one.
    pub(crate) client_key: Option<String>,
    pub(crate) pty_size: Arc<Mutex<Option<(u32, u32)>>>,
    handle: tokio::runtime::Runtime,
    stop: Arc<AtomicBool>,
}

impl Fixture {
    pub(crate) fn start(policy: Policy) -> Fixture {
        let served = Arc::new(AtomicBool::new(false));
        let stop = Arc::new(AtomicBool::new(false));
        let port = Arc::new(AtomicU16::new(0));
        let pty_size = Arc::new(Mutex::new(None));

        let runtime = tokio::runtime::Builder::new_multi_thread()
            .worker_threads(2)
            .enable_all()
            .build()
            .expect("runtime");

        // Generated by ssh-keygen rather than in-process: `PrivateKey::random`
        // wants an RNG from the exact `rand_core` ssh-key was built against,
        // and chasing that version across the tree is a worse dependency than
        // one subprocess. Committing a fixed private key would be worse still,
        // test-only or not.
        let key = generate_key();

        // Only the key-first policy needs a client key; the others would pay
        // for a second ssh-keygen and never offer it.
        let (client_key, authorized) = match policy {
            Policy::PublicKeyThenKeyboardInteractive(_) => {
                let pem = generate_key_pem();
                let parsed = russh::keys::decode_secret_key(&pem, None).expect("decode key");
                (Some(pem), Some(Arc::new(parsed.public_key().clone())))
            }
            _ => (None, None),
        };

        let config = Arc::new(russh::server::Config {
            keys: vec![key],
            auth_rejection_time: std::time::Duration::from_millis(50),
            ..Default::default()
        });

        let listen_served = served.clone();
        let listen_port = port.clone();
        let listen_stop = stop.clone();
        let listen_pty_size = pty_size.clone();
        runtime.spawn(async move {
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
                .await
                .expect("bind");
            listen_port.store(listener.local_addr().unwrap().port(), Ordering::SeqCst);

            let mut server = TestSshServer {
                policy,
                authorized,
                served: listen_served,
                pty_size: listen_pty_size,
            };
            loop {
                if listen_stop.load(Ordering::SeqCst) {
                    return;
                }
                let Ok(Ok((stream, addr))) =
                    tokio::time::timeout(Duration::from_millis(200), listener.accept()).await
                else {
                    continue;
                };
                let handler = server.new_client(Some(addr));
                let config = config.clone();
                tokio::spawn(async move {
                    let _ = russh::server::run_stream(config, stream, handler).await;
                });
            }
        });

        // The port is only known once the listener is up.
        let deadline = Instant::now() + Duration::from_secs(5);
        while port.load(Ordering::SeqCst) == 0 && Instant::now() < deadline {
            std::thread::sleep(Duration::from_millis(10));
        }

        Fixture {
            port: port.load(Ordering::SeqCst),
            served,
            client_key,
            pty_size,
            handle: runtime,
            stop,
        }
    }

    /// The key auth for the policy that authorised one.
    pub(crate) fn key(&self) -> SshAuth {
        SshAuth::PrivateKey {
            pem: self
                .client_key
                .clone()
                .expect("no client key was generated"),
            passphrase: None,
        }
    }

    /// Connects with the given auth, answering nothing, and reports what
    /// happened.
    pub(crate) fn attempt(&self, user: &str, auth: SshAuth) -> Result<String, String> {
        self.attempt_with(user, auth, unasked()).outcome
    }

    /// Connects, letting `plan` answer whatever the server asks.
    pub(crate) fn attempt_with(&self, user: &str, auth: SshAuth, plan: Plan) -> Attempt {
        let recorder = Arc::new(Recorder::default());
        let session = SshSession::connect(
            SshConfig {
                host: "127.0.0.1".to_string(),
                port: self.port,
                username: user.to_string(),
                auth,
                term: "xterm-256color".to_string(),
                cols: 80,
                rows: 24,
            },
            Box::new(Events(recorder.clone())),
        );

        let outcome = self.pump(&session, &recorder, &plan, Duration::from_secs(15));
        Attempt {
            outcome,
            asked: recorder.asked.lock().unwrap().clone(),
        }
    }

    /// Serves challenges and waits for the connection to settle one way or
    /// the other.
    fn pump(
        &self,
        session: &SshSession,
        recorder: &Recorder,
        plan: &Plan,
        within: Duration,
    ) -> Result<String, String> {
        let deadline = Instant::now() + within;
        loop {
            for challenge in recorder.take_unserved() {
                plan(&challenge, session);
            }
            if recorder.connected.load(Ordering::SeqCst) {
                // Give the greeting a moment to arrive.
                let until = Instant::now() + Duration::from_secs(3);
                while Instant::now() < until {
                    let seen = String::from_utf8_lossy(&recorder.data.lock().unwrap()).to_string();
                    if seen.contains(GREETING) {
                        session.disconnect();
                        return Ok(seen);
                    }
                    std::thread::sleep(Duration::from_millis(30));
                }
                session.disconnect();
                return Ok(String::new());
            }
            if let Some(reason) = recorder.closed.lock().unwrap().clone() {
                return Err(reason);
            }
            if Instant::now() >= deadline {
                session.disconnect();
                return Err("timed out".to_string());
            }
            std::thread::sleep(Duration::from_millis(20));
        }
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::SeqCst);
        // Nothing here may outlive the test; the runtime owns the listener.
        let runtime = std::mem::replace(
            &mut self.handle,
            tokio::runtime::Builder::new_current_thread()
                .build()
                .unwrap(),
        );
        runtime.shutdown_timeout(Duration::from_millis(500));
    }
}

/// A throwaway ed25519 key, made by ssh-keygen, in its armoured text form.
pub(crate) fn generate_key_pem() -> String {
    let dir = std::env::temp_dir().join(format!(
        "tako-testkey-{}-{:?}-{:?}",
        std::process::id(),
        std::thread::current().id(),
        Instant::now()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("temp dir");
    let path = dir.join("host");

    let status = std::process::Command::new("ssh-keygen")
        .args(["-q", "-t", "ed25519", "-N", ""])
        .arg("-f")
        .arg(&path)
        // Closed, not inherited: ssh-keygen prompts before overwriting and an
        // inherited stdin turns that into a test that hangs with no output.
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .expect("run ssh-keygen");
    assert!(status.success(), "ssh-keygen failed");

    let pem = std::fs::read_to_string(&path).expect("read key");
    let _ = std::fs::remove_dir_all(&dir);
    pem
}

/// The same, decoded, for the server to serve as its host key.
pub(crate) fn generate_key() -> russh::keys::PrivateKey {
    russh::keys::decode_secret_key(&generate_key_pem(), None).expect("decode key")
}

pub(crate) fn password(text: &str) -> SshAuth {
    SshAuth::Password {
        password: text.to_string(),
    }
}
